name: Scheduled Script Run

on:
  schedule:
    - cron: '0 3 * * *'     # Every day at 3 AM UTC
    - cron: '0 22 * * 5'    # Every Friday at 10 PM UTC
    - cron: '0 17 * * 6'    # Every Saturday at 5 PM UTC
    - cron: '0 20 * * 6'    # Every Saturday at 8 PM UTC
    - cron: '0 21 * * 0'    # Every Sunday at 9 PM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r preprocessing/requirements.txt

    - name: Run the script
      run: |
        cd preprocessing
        python scrape_li.py  # Replace with your script's name
